version: "1.0"
info:
  model: int-scaffold
packages:
- name: EdgeEmpty
  gitServerName: testEdgeProjects
  gitUrl: https://github.com/rlakshitha0912/EdgeEmpty
  gitUsername: rlakshitha0912
  gitToken: edge.scaffolding.EdgeEmpty.testEdgeProjects.gitToken
  gitBranch: main
