version: "1.0"
info:
  model: int-scaffold
services:
- serviceName: edge.empty.integrations:test
  packages:
  - name: EdgeEmpty
    version: "1.0"
packages:
- name: EdgeEmpty
  gitServerName: testEdgeProjects
  gitUrl: https://github.com/rlakshitha0912/EdgeEmpty
  gitUsername: rlakshitha0912
  gitToken: edge.scaffolding.EdgeEmpty.testEdgeProjects.gitToken
  gitBranch: main
